name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: visit project folder
      run: cd ~/test 
    
    - name: Install last version
      run: git pull origin main 

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Restart application
      run: pm2 restart all


# name: Deploy to DigitalOcean Droplet

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: self-hosted

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
    
#     - name: visit project folder
#       run: cd ~/test 
    
#     - name: Install last version
#       run: git pull origin main 

#     - name: Install dependencies
#       run: npm install

#     - name: Build project
#       run: npm run build

#     - name: Restart application
#       run: cp ~/test/dist /var/www/test -r

