name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build
    
    # - name: Backup old version
    #   run: cp -r /var/www/test ~/test_backup_$(date +'%Y%m%d%H%M%S')

    - name: Remove old version
      run: sudo su rm -r /var/www/test

    - name: Set new version
      run: sudo cp -r dist /var/www/test

    - name: Reload Nginx
      run: sudo systemctl reload nginx

    # - name: Restart application
    #   run: pm2 restart all

# name: Deploy to DigitalOcean Droplet

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: self-hosted

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Install dependencies
#       run: npm install

#     - name: Build project
#       run: npm run build


# name: Deploy Vue.js App to Nginx

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Set up Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: '16'

#     - name: Install dependencies
#       run: npm install

#     - name: Build the Vue.js app
#       run: npm run build

#     - name: Deploy to server
#       uses: appleboy/scp-action@v0.1.3
#       with:
#         host: ${{ secrets.HOST }}
#         username: ${{ secrets.USERNAME }}
#         password: ${{ secrets.PASSWORD }}
#         source: "dist/*"
#         target: "/var/www/test"
#         rm: true

#     - name: Restart Nginx
#       run: |
#         ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "sudo systemctl restart nginx"
